// Compiles a dart2wasm-generated main module from `source` which can then
// be instantiated via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm module from `bytes` which is then
// instantiable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModules` is a JS function that takes an array of module names
  //   matching wasm files produced by the dart2wasm compiler. It also takes a
  //   callback that should be invoked for each loaded module with 2 arguments:
  //   (1) the module name, (2) the loaded module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The callback
  //   returns a Promise that resolves when the module is instantiated.
  //   loadDeferredModules should return a Promise that resolves when all the
  //   modules have been loaded and the callback promises have resolved.
  // `loadDeferredId` is a JS function that takes load ID produced by the
  //   compiler when the `use-load-ids` option is passed. Each load ID maps to
  //   one or more wasm files as specified in the emitted JSON file. It also
  //   takes a callback that should be invoked for each loaded module with 2
  //   arguments: (1) the module name, (2) the loaded module in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  //   The callback returns a Promise that resolves when the module is
  //   instantiated.
  //   loadDeferredId should return a Promise that resolves when all the
  //   modules have been loaded and the callback promises have resolved.
  async instantiate(additionalImports, {loadDeferredModules, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            AB: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      AC: Function.prototype.call.bind(DataView.prototype.getInt16),
      AD: x0 => x0.devicePixelRatio,
      AE: x0 => x0.languages,
      AF: x0 => x0.deltaX,
      AG: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      AH: x0 => x0.data,
      AI: x0 => x0.offsetHeight,
      AJ: x0 => x0.readyState,
      AK: x0 => x0.completed,
      AL: (x0,x1) => x0.render(x1),
      AM: x0 => x0.body,
      AN: (x0,x1) => x0.copyTo(x1),
      AO: x0 => x0.buffer,
      AP: (x0,x1,x2) => x0.setBigInt64(x1,x2),
      AQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      AR: x0 => x0.name,
      AS: x0 => x0.ctrlKey,
      AT: x0 => x0.children,
      AU: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      AV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      AW: (x0,x1) => x0.setSinkId(x1),
      AX: (x0,x1) => x0.setTilt(x1),
      AY: () => ({}),
      AZ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Aa: () => new libphonenumber.PhoneNumber(),
      Ab: x0 => x0.timeCreated,
      Ac: (x0,x1) => x0.createScriptURL(x1),
      Ad: x0 => x0.isAnonymous,
      Ae: x0 => x0.response,
      Af: () => globalThis.firebase_firestore.VectorValue,
      B: s => printToConsole(s),
      BB: b => !!b,
      BC: o => o instanceof Uint8ClampedArray,
      BD: x0 => x0.height,
      BE: (x0,x1) => x0.observe(x1),
      BF: x0 => x0.wheelDeltaY,
      BG: x0 => x0.v8BreakIterator,
      BH: (x0,x1) => { x0.scrollTop = x1 },
      BI: x0 => x0.offsetWidth,
      BJ: x0 => x0.total,
      BK: x0 => x0.ready,
      BL: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      BM: (x0,x1) => { x0.download = x1 },
      BN: (x0,x1) => { x0.height = x1 },
      BO: (x0,x1) => x0.sqlite3_errstr(x1),
      BP: x0 => new Worker(x0),
      BQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      BR: x0 => globalThis.IDBKeyRange.only(x0),
      BS: x0 => x0.isComposing,
      BT: x0 => ({url: x0}),
      BU: (x0,x1) => x0.append(x1),
      BV: x0 => x0.head,
      BW: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      BX: (x0,x1) => x0.setZoom(x1),
      BY: (x0,x1) => { x0.zIndex = x1 },
      BZ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Ba: (x0,x1) => x0.getCountryCodeForRegion(x1),
      Bb: x0 => x0.size,
      Bc: (x0,x1,x2) => x0.createScript(x1,x2),
      Bd: x0 => x0.emailVerified,
      Be: x0 => x0.error,
      Bf: x0 => x0.longitude,
      C: Function.prototype.call.bind(Number.prototype.toString),
      CB: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      CC: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Uint8Array) return 1;
        return 2;
      },
      CD: x0 => x0.width,
      CE: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      CF: x0 => x0.wheelDeltaX,
      CG: () => globalThis.Intl,
      CH: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      CI: x0 => x0.stopPropagation(),
      CJ: x0 => x0.loaded,
      CK: x0 => x0.tracks,
      CL: (x0,x1) => x0.toBlob(x1),
      CM: (x0,x1) => { x0.href = x1 },
      CN: (x0,x1) => { x0.width = x1 },
      CO: (x0,x1) => x0.sqlite3_errmsg(x1),
      CP: (x0,x1,x2) => new DataView(x0,x1,x2),
      CQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      CR: (x0,x1,x2) => x0.put(x1,x2),
      CS: x0 => x0.code,
      CT: (x0,x1,x2) => ({files: x0,title: x1,text: x2}),
      CU: (x0,x1) => { x0.onpause = x1 },
      CV: (x0,x1) => { x0.onerror = x1 },
      CW: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      CX: (x0,x1) => x0.setHeading(x1),
      CY: (x0,x1) => { x0.content = x1 },
      CZ: (x0,x1,x2) => x0.open(x1,x2),
      Ca: (x0,x1) => x0.of(x1),
      Cb: x0 => x0.name,
      Cc: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Cd: x0 => x0.email,
      Ce: x0 => x0.id,
      Cf: x0 => x0.latitude,
      D: Function.prototype.call.bind(BigInt.prototype.toString),
      DB: (x0,x1) => x0.focus(x1),
      DC: Function.prototype.call.bind(DataView.prototype.setInt8),
      DD: x0 => x0.screen,
      DE: x0 => new ResizeObserver(x0),
      DF: x0 => x0.key,
      DG: (x0,x1) => x0.segment(x1),
      DH: (x0,x1) => { x0.value = x1 },
      DI: x0 => x0.disabled,
      DJ: x0 => x0.upload,
      DK: () => globalThis.window.ImageDecoder,
      DL: (o, p, v) => o[p] = v,
      DM: x0 => x0.ok,
      DN: (x0,x1) => x0.toDataURL(x1),
      DO: (x0,x1) => x0.sqlite3_error_offset(x1),
      DP: () => globalThis.Uint8Array,
      DQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      DR: (x0,x1) => x0.getKey(x1),
      DS: x0 => x0.repeat,
      DT: (x0,x1) => ({files: x0,text: x1}),
      DU: (x0,x1) => { x0.onplay = x1 },
      DV: (x0,x1) => { x0.onload = x1 },
      DW: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      DX: (x0,x1) => x0.setOptions(x1),
      DY: (x0,x1) => { x0.innerHTML = x1 },
      DZ: x0 => x0.map,
      Da: (x0,x1,x2) => x0.format(x1,x2),
      Db: x0 => x0.metageneration,
      Dc: (o, p) => delete o[p],
      Dd: x0 => x0.displayName,
      De: x0 => x0.maxTouchPoints,
      Df: () => globalThis.firebase_firestore.GeoPoint,
      E: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 4;
        if (frames[0].startsWith('Error')) {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      EB: () => ({}),
      EC: Function.prototype.call.bind(DataView.prototype.getInt8),
      ED: o => {
        if (o === null || o === undefined) return 0;
        if (typeof(o) === 'string') return 1;
        return 2;
      },
      EE: (x0,x1) => x0.getPropertyValue(x1),
      EF: x0 => x0.identifier,
      EG: x0 => x0.index,
      EH: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      EI: (x0,x1) => { x0.min = x1 },
      EJ: x0 => x0.responseURL,
      EK: (x0,x1) => x0.get(x1),
      EL: (x0,x1,x2,x3) => ({id: x0,width: x1,height: x2,data: x3}),
      EM: x0 => globalThis.URL.createObjectURL(x0),
      EN: (x0,x1,x2,x3) => x0.drawImage(x1,x2,x3),
      EO: (x0,x1) => x0.sqlite3_extended_errcode(x1),
      EP: x0 => x0.communicationBuffer,
      EQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      ER: (x0,x1) => x0.delete(x1),
      ES: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      ET: (x0,x1) => ({files: x0,title: x1}),
      EU: (x0,x1) => { x0.pointerEvents = x1 },
      EV: (x0,x1) => { x0.src = x1 },
      EW: (x0,x1) => { x0.oncancel = x1 },
      EX: () => ({}),
      EY: (x0,x1) => { x0.innerHTML = x1 },
      EZ: x0 => x0.close(),
      Ea: () => globalThis.libphonenumber.PhoneNumberFormat.INTERNATIONAL,
      Eb: x0 => x0.md5Hash,
      Ec: (x0,x1) => { x0.text = x1 },
      Ed: x0 => globalThis.firebase_auth.multiFactor(x0),
      Ee: x0 => x0.hardwareConcurrency,
      Ef: (x0,x1) => x0.data(x1),
      F: () => new Error().stack,
      FB: (o, p, v) => o[p] = v,
      FC: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Int8Array) return 1;
        return 2;
      },
      FD: x0 => x0.tabIndex,
      FE: x0 => globalThis.parseFloat(x0),
      FF: x0 => x0.touches,
      FG: x0 => x0.next(),
      FH: (x0,x1) => { x0.value = x1 },
      FI: (x0,x1) => { x0.max = x1 },
      FJ: x0 => x0.statusText,
      FK: x0 => x0.body,
      FL: x0 => x0.arrayBuffer(),
      FM: x0 => globalThis.URL.revokeObjectURL(x0),
      FN: (x0,x1) => x0.getContext(x1),
      FO: (x0,x1) => x0.sqlite3_step(x1),
      FP: () => globalThis.Int32Array,
      FQ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      FR: (x0,x1) => x0.put(x1),
      FS: (x0,x1) => x0.removeAttribute(x1),
      FT: x0 => ({files: x0}),
      FU: (x0,x1) => { x0.transformOrigin = x1 },
      FV: (x0,x1) => { x0.crossOrigin = x1 },
      FW: (x0,x1) => { x0.onchange = x1 },
      FX: (x0,x1) => { x0.mapId = x1 },
      FY: x0 => x0.trustedTypes,
      FZ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Fa: () => globalThis.libphonenumber.PhoneNumberFormat.NATIONAL,
      Fb: x0 => x0.generation,
      Fc: () => globalThis.console,
      Fd: x0 => x0.toJSON(),
      Fe: x0 => x0.vendorSub,
      Ff: x0 => x0.nanoseconds,
      G: s => JSON.stringify(s),
      GB: () => [],
      GC: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      GD: (x0,x1) => x0.contains(x1),
      GE: (x0,x1) => x0.getComputedStyle(x1),
      GF: x0 => x0.pressure,
      GG: x0 => x0.value,
      GH: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      GI: (x0,x1) => { x0.disabled = x1 },
      GJ: x0 => x0.getAllResponseHeaders(),
      GK: x0 => x0.headers,
      GL: x0 => x0.promise,
      GM: (a, s, e) => a.splice(s, e),
      GN: x0 => x0.format,
      GO: (x0,x1,x2,x3,x4) => x0.dart_sqlite3_bind_blob(x1,x2,x3,x4),
      GP: x0 => x0.byteLength,
      GQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2) { return wasmFunction(f,arguments.length,x0,x1,x2) }),
      GR: (x0,x1,x2) => x0.postMessage(x1,x2),
      GS: x0 => x0.load(),
      GT: (x0,x1) => ({title: x0,text: x1}),
      GU: (x0,x1) => { x0.objectFit = x1 },
      GV: (x0,x1) => { x0.lang = x1 },
      GW: x0 => x0.type,
      GX: (x0,x1) => { x0.styles = x1 },
      GY: x0 => x0.trustedTypes,
      GZ: (x0,x1) => { x0.map = x1 },
      Ga: () => globalThis.libphonenumber.PhoneNumberType.FIXED_LINE,
      Gb: x0 => x0.fullPath,
      Gc: x0 => x0.trustedTypes,
      Gd: x0 => x0.user,
      Ge: x0 => x0.productSub,
      Gf: x0 => x0.seconds,
      H: Function.prototype.call.bind(Number.prototype.toString),
      HB: (a, i) => a.push(i),
      HC: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      HD: x0 => x0.activeElement,
      HE: x0 => x0.documentElement,
      HF: x0 => x0.tiltY,
      HG: x0 => x0.done,
      HH: x0 => x0.value,
      HI: (x0,x1) => { x0.scrollLeft = x1 },
      HJ: x0 => x0.status,
      HK: x0 => ({type: x0}),
      HL: (x0,x1) => { x0.fillStyle = x1 },
      HM: x0 => x0.input,
      HN: () => new MessageChannel(),
      HO: (x0,x1) => x0.dart_sqlite3_malloc(x1),
      HP: x0 => x0.synchronizationBuffer,
      HQ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      HR: x0 => x0.port2,
      HS: (x0,x1) => { x0.loop = x1 },
      HT: x0 => ({text: x0}),
      HU: x0 => x0.getSupportedConstraints(),
      HV: (x0,x1) => { x0.type = x1 },
      HW: x0 => x0.lastModified,
      HX: (x0,x1) => { x0.streetViewControl = x1 },
      HY: (x0,x1) => { x0.innerText = x1 },
      HZ: x0 => new google.maps.Marker(x0),
      Ha: () => globalThis.libphonenumber.PhoneNumberType.MOBILE,
      Hb: x0 => x0.customMetadata,
      Hc: (x0,x1) => { x0.languageCode = x1 },
      Hd: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromResult(x0),
      He: x0 => x0.product,
      Hf: () => globalThis.firebase_firestore.Timestamp,
      I: Function.prototype.call.bind(String.prototype.indexOf),
      IB: x0 => new Int8Array(x0),
      IC: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      ID: x0 => x0.parentNode,
      IE: x0 => x0.computedStyleMap(),
      IF: x0 => x0.tiltX,
      IG: (o, m, a) => o[m].apply(o, a),
      IH: x0 => x0.selectionDirection,
      II: (x0,x1) => { x0.spellcheck = x1 },
      IJ: x0 => x0.response,
      IK: (x0,x1) => new Blob(x0,x1),
      IL: x0 => x0.width,
      IM: (a, i) => a.splice(i, 1)[0],
      IN: x0 => new BroadcastChannel(x0),
      IO: (x0,x1,x2,x3,x4) => x0.dart_sqlite3_bind_text(x1,x2,x3,x4),
      IP: (x0,x1,x2) => x0.postMessage(x1,x2),
      IQ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      IR: x0 => x0.terminate(),
      IS: (x0,x1) => { x0.volume = x1 },
      IT: () => ({}),
      IU: x0 => ({ideal: x0}),
      IV: (x0,x1) => { x0.defer = x1 },
      IW: x0 => x0.name,
      IX: (x0,x1) => { x0.fullscreenControl = x1 },
      IY: (x0,x1) => { x0.className = x1 },
      IZ: (x0,x1,x2) => x0.set(x1,x2),
      Ia: x0 => x0.language,
      Ib: x0 => x0.contentType,
      Ic: x0 => globalThis.firebase_auth.useDeviceLanguage(x0),
      Id: x0 => x0.username,
      Ie: x0 => x0.platform,
      If: () => globalThis.firebase_firestore.DocumentReference,
      J: (s, p, i) => s.lastIndexOf(p, i),
      JB: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      JC: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      JD: x0 => x0.tagName,
      JE: (x0,x1) => x0.get(x1),
      JF: x0 => x0.pointerType,
      JG: x0 => x0.iterator,
      JH: x0 => x0.selectionStart,
      JI: (x0,x1) => { x0.disabled = x1 },
      JJ: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      JK: (x0,x1) => x0.createImageBitmap(x1),
      JL: x0 => x0.numPages,
      JM: (x0,x1,x2) => x0.postMessage(x1,x2),
      JN: x0 => globalThis.Array.isArray(x0),
      JO: (x0,x1,x2,x3) => x0.sqlite3_bind_double(x1,x2,x3),
      JP: x0 => new SharedArrayBuffer(x0),
      JQ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      JR: (x0,x1) => new SharedWorker(x0,x1),
      JS: (x0,x1) => { x0.muted = x1 },
      JT: (x0,x1,x2) => new File(x0,x1,x2),
      JU: (x0,x1,x2) => ({width: x0,height: x1,deviceId: x2}),
      JV: (x0,x1) => { x0.async = x1 },
      JW: (x0,x1) => x0.item(x1),
      JX: (x0,x1) => { x0.mapTypeControl = x1 },
      JY: () => ({}),
      JZ: x0 => x0.getMap(),
      Ja: (x0,x1,x2) => x0.parse(x1,x2),
      Jb: x0 => x0.contentLanguage,
      Jc: (x0,x1,x2) => ({errorMap: x0,persistence: x1,popupRedirectResolver: x2}),
      Jd: x0 => x0.providerId,
      Je: x0 => x0.languages,
      Jf: x0 => x0.ref,
      K: o => o,
      KB: x0 => new Uint8Array(x0),
      KC: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      KD: x0 => x0.target,
      KE: (o, p) => p in o,
      KF: x0 => x0.pointerId,
      KG: () => globalThis.Symbol,
      KH: x0 => x0.selectionEnd,
      KI: (x0,x1) => x0.getRandomValues(x1),
      KJ: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      KK: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9) => x0.drawImage(x1,x2,x3,x4,x5,x6,x7,x8,x9),
      KL: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      KM: x0 => x0.contentWindow,
      KN: x0 => x0.table,
      KO: (x0,x1,x2,x3) => x0.sqlite3_bind_int64(x1,x2,x3),
      KP: (x0,x1,x2,x3) => ({clientVersion: x0,root: x1,synchronizationBuffer: x2,communicationBuffer: x3}),
      KQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return wasmFunction(f,arguments.length,x0,x1,x2,x3,x4) }),
      KR: x0 => x0.start(),
      KS: (x0,x1) => { x0.src = x1 },
      KT: (x0,x1) => { x0.type = x1 },
      KU: (x0,x1) => ({width: x0,height: x1}),
      KV: x0 => x0.stream,
      KW: x0 => x0.length,
      KX: (x0,x1) => { x0.rotateControl = x1 },
      KY: (x0,x1) => { x0.draggable = x1 },
      KZ: (x0,x1) => x0.setPosition(x1),
      Ka: (x0,x1) => x0.isValidNumber(x1),
      Kb: x0 => x0.contentEncoding,
      Kc: (x0,x1) => globalThis.firebase_auth.initializeAuth(x0,x1),
      Kd: x0 => x0.profile,
      Ke: x0 => x0.deviceMemory,
      Kf: x0 => x0.id,
      L: o => {
        if (o === undefined || o === null) return 0;
        if (typeof o === 'number') return 1;
        return 2;
      },
      LB: x0 => new Uint8ClampedArray(x0),
      LC: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      LD: x0 => x0.clientY,
      LE: (x0,x1) => { x0.textContent = x1 },
      LF: x0 => x0.getCoalescedEvents(),
      LG: (x0,x1) => new Intl.Segmenter(x0,x1),
      LH: x0 => x0.value,
      LI: () => globalThis.crypto,
      LJ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      LK: (x0,x1,x2,x3,x4) => x0.getImageData(x1,x2,x3,x4),
      LL: (x0,x1) => x0.send(x1),
      LM: (x0,x1) => { x0.allow = x1 },
      LN: x0 => x0.kind,
      LO: x0 => globalThis.BigInt(x0),
      LP: x0 => x0.close(),
      LQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return wasmFunction(f,arguments.length,x0,x1,x2,x3) }),
      LR: x0 => x0.port,
      LS: x0 => x0.message,
      LT: x0 => x0.read(),
      LU: (x0,x1,x2) => ({width: x0,height: x1,facingMode: x2}),
      LV: x0 => x0.paused,
      LW: x0 => x0.files,
      LX: (x0,x1) => { x0.cameraControl = x1 },
      LY: (x0,x1) => { x0.opacity = x1 },
      LZ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      La: (x0,x1) => x0.getNumberType(x1),
      Lb: x0 => x0.contentDisposition,
      Lc: () => globalThis.firebase_auth.browserPopupRedirectResolver,
      Ld: x0 => x0.isNewUser,
      Le: x0 => x0.appVersion,
      Lf: x0 => x0.doc,
      M: x0 => x0.index,
      MB: x0 => new Int16Array(x0),
      MC: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      MD: x0 => x0.clientX,
      ME: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      MF: (x0,x1) => x0.getModifierState(x1),
      MG: x0 => x0.Segmenter,
      MH: x0 => x0.selectionDirection,
      MI: l => new DataView(new ArrayBuffer(l)),
      MJ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      MK: x0 => x0.close(),
      ML: x0 => x0.send(),
      MM: (x0,x1) => { x0.id = x1 },
      MN: (x0,x1) => x0.postMessage(x1),
      MO: (x0,x1,x2) => x0.sqlite3_bind_null(x1,x2),
      MP: x0 => x0.getSize(),
      MQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return wasmFunction(f,arguments.length,x0,x1,x2,x3) }),
      MR: (x0,x1) => { x0.cookie = x1 },
      MS: x0 => x0.code,
      MT: (x0,x1) => x0.getType(x1),
      MU: x0 => x0.deviceId,
      MV: (x0,x1,x2,x3) => x0.drawImage(x1,x2,x3),
      MW: (x0,x1) => x0.replaceChildren(x1),
      MX: (x0,x1) => { x0.gestureHandling = x1 },
      MY: (x0,x1) => { x0.visible = x1 },
      MZ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Ma: x0 => x0.getCountryCode(),
      Mb: x0 => x0.cacheControl,
      Mc: () => globalThis.firebase_auth.debugErrorMap,
      Md: x0 => globalThis.firebase_auth.getAdditionalUserInfo(x0),
      Me: x0 => x0.appName,
      Mf: x0 => x0.newIndex,
      N: o => String(o),
      NB: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      NC: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      ND: (x0,x1,x2) => x0.setAttribute(x1,x2),
      NE: x0 => x0.matches,
      NF: s => s.trimLeft(),
      NG: x0 => x0.buffer,
      NH: x0 => x0.selectionStart,
      NI: (a, i) => a.splice(i, 1),
      NJ: x0 => x0.withCredentials,
      NK: x0 => x0.data,
      NL: (x0,x1) => { x0.onreadystatechange = x1 },
      NM: x0 => x0.data,
      NN: (x0,x1) => ({kind: x0,table: x1}),
      NO: (x0,x1) => x0.sqlite3_bind_parameter_count(x1),
      NP: (x0,x1) => x0.truncate(x1),
      NQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return wasmFunction(f,arguments.length,x0,x1,x2,x3) }),
      NR: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      NS: x0 => x0.error,
      NT: x0 => x0.text(),
      NU: x0 => x0.getCapabilities(),
      NV: (x0,x1,x2) => x0.readBarcodes(x1,x2),
      NW: (x0,x1) => { x0.accept = x1 },
      NX: (x0,x1) => { x0.zoomControl = x1 },
      NY: (x0,x1) => { x0.zIndex = x1 },
      NZ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Na: (x0,x1) => x0.getRegionCodeForNumber(x1),
      Nb: x0 => x0.bucket,
      Nc: () => globalThis.firebase_auth.browserSessionPersistence,
      Nd: (x0,x1) => globalThis.firebase_auth.signInWithCredential(x0,x1),
      Ne: x0 => x0.appCodeName,
      Nf: x0 => x0.oldIndex,
      O: o => o === undefined,
      OB: x0 => new Uint16Array(x0),
      OC: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      OD: x0 => x0.getBoundingClientRect(),
      OE: (x0,x1) => x0.matchMedia(x1),
      OF: s => s.toUpperCase(),
      OG: x0 => x0.wasmMemory,
      OH: x0 => x0.selectionEnd,
      OI: a => a.pop(),
      OJ: (x0,x1) => { x0.timeout = x1 },
      OK: (x0,x1) => x0.getContext(x1),
      OL: x0 => x0.abort(),
      OM: (x0,x1) => { x0.src = x1 },
      ON: () => ({}),
      OO: (x0,x1) => x0.sqlite3_stmt_isexplain(x1),
      OP: x0 => ({at: x0}),
      OQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      OR: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      OS: (x0,x1) => x0.start(x1),
      OT: x0 => x0.types,
      OU: () => ({}),
      OV: x0 => x0.text,
      OW: (x0,x1) => { x0.multiple = x1 },
      OX: (x0,x1) => { x0.maxZoom = x1 },
      OY: (x0,x1) => { x0.title = x1 },
      OZ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Oa: x0 => x0.getNationalNumber(),
      Ob: x0 => globalThis.firebase_storage.getMetadata(x0),
      Oc: () => globalThis.firebase_auth.browserLocalPersistence,
      Od: (x0,x1,x2) => globalThis.firebase_auth.signInWithEmailLink(x0,x1,x2),
      Oe: x0 => x0.onLine,
      Of: x0 => x0.type,
      P: (x0,x1) => x0.exec(x1),
      PB: x0 => new Int32Array(x0),
      PC: (x0,x1) => x0.querySelector(x1),
      PD: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      PE: x0 => x0.matches,
      PF: x0 => x0.pop(),
      PG: () => globalThis.window._flutter_skwasmInstance,
      PH: x0 => x0.keyCode,
      PI: (map, o, v) => map.set(o, v),
      PJ: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      PK: (x0,x1) => { x0.height = x1 },
      PL: x0 => x0.status,
      PM: (x0,x1) => { x0.srcdoc = x1 },
      PN: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      PO: (x0,x1) => x0.dart_sqlite3_free(x1),
      PP: (x0,x1) => x0.write(x1),
      PQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      PR: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      PS: (x0,x1) => x0.end(x1),
      PT: x0 => x0.clipboard,
      PU: (x0,x1) => x0.applyConstraints(x1),
      PV: x0 => x0.format,
      PW: (x0,x1) => { x0.type = x1 },
      PX: (x0,x1) => { x0.minZoom = x1 },
      PY: (x0,x1) => { x0.icon = x1 },
      PZ: (x0,x1) => x0.setMap(x1),
      Pa: () => globalThis.libphonenumber.PhoneNumberFormat.E164,
      Pb: x0 => x0.metadata,
      Pc: () => globalThis.firebase_auth.indexedDBLocalPersistence,
      Pd: (x0,x1,x2) => x0.verifyPhoneNumber(x1,x2),
      Pe: (x0,x1) => x0.delete(x1),
      Pf: x0 => x0.docChanges(),
      Q: (x0,x1) => { x0.lastIndex = x1 },
      QB: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      QC: (x0,x1) => x0.item(x1),
      QD: s => new Date(s * 1000).getTimezoneOffset() * 60,
      QE: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      QF: x0 => x0.flags,
      QG: () => new TextDecoder(),
      QH: (x0,x1) => x0.scrollIntoView(x1),
      QI: (map, o) => map.get(o),
      QJ: (x0,x1) => { x0.withCredentials = x1 },
      QK: (x0,x1) => { x0.width = x1 },
      QL: (o, t) => typeof o === t,
      QM: x0 => x0.text(),
      QN: (x0,x1,x2,x3) => x0.request(x1,x2,x3),
      QO: (x0,x1,x2,x3,x4,x5,x6) => x0.sqlite3_prepare_v3(x1,x2,x3,x4,x5,x6),
      QP: (x0,x1,x2) => x0.write(x1,x2),
      QQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return wasmFunction(f,arguments.length,x0,x1,x2,x3,x4) }),
      QR: x0 => x0.origin,
      QS: x0 => x0.length,
      QT: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      QU: (x0,x1) => { x0.whiteBalanceMode = x1 },
      QV: x0 => x0.bytes,
      QW: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      QX: (x0,x1) => { x0.mapTypeId = x1 },
      QY: () => ({}),
      QZ: (x0,x1) => x0.setOptions(x1),
      Qa: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2) { return wasmFunction(f,arguments.length,x0,x1,x2) }),
      Qb: x0 => x0.bytesTransferred,
      Qc: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromError(x0),
      Qd: (x0,x1,x2) => new firebase_auth.RecaptchaVerifier(x0,x1,x2),
      Qe: (x0,x1) => globalThis.firebase_firestore.doc(x0,x1),
      Qf: x0 => x0.docs,
      R: o => o,
      RB: x0 => new Uint32Array(x0),
      RC: x0 => x0.length,
      RD: Date.now,
      RE: f => f.dartFunction,
      RF: (a, s) => a.join(s),
      RG: (d, digits) => d.toFixed(digits),
      RH: x0 => x0.multiViewEnabled,
      RI: () => new WeakMap(),
      RJ: (x0,x1) => { x0.responseType = x1 },
      RK: (x0,x1) => x0.createElement(x1),
      RL: x0 => x0.response,
      RM: (x0,x1,x2) => ({method: x0,headers: x1,body: x2}),
      RN: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      RO: (x0,x1,x2,x3,x4,x5) => x0.sqlite3_exec(x1,x2,x3,x4,x5),
      RP: x0 => x0.createSyncAccessHandle(),
      RQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      RR: (x0,x1) => x0.sqlite3_changes(x1),
      RS: x0 => x0.buffered,
      RT: x0 => x0.firstElementChild,
      RU: x0 => x0.whiteBalanceMode,
      RV: x0 => x0.y,
      RW: (x0,x1,x2,x3) => x0.toBlob(x1,x2,x3),
      RX: () => globalThis.google.maps.MapTypeId.ROADMAP,
      RY: x0 => new Blob(x0),
      RZ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Ra: (x0,x1) => { x0.nativeCommunication = x1 },
      Rb: x0 => x0.totalBytes,
      Rc: x0 => x0.session,
      Rd: x0 => new firebase_auth.PhoneAuthProvider(x0),
      Re: x0 => x0.id,
      Rf: x0 => globalThis.firebase_firestore.getDocs(x0),
      S: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      SB: x0 => new Float32Array(x0),
      SC: (x0,x1) => x0.querySelectorAll(x1),
      SD: (handle) => clearTimeout(handle),
      SE: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      SF: (x0,x1) => x0.error(x1),
      SG: x0 => x0.maxHeight,
      SH: (x0,x1) => x0.replaceWith(x1),
      SI: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      SJ: x0 => x0.naturalHeight,
      SK: () => globalThis.document,
      SL: x0 => x0.getAllResponseHeaders(),
      SM: (x0,x1,x2) => x0.fetch(x1,x2),
      SN: (o,s,v) => o[s] = v,
      SO: (x0,x1) => x0.sqlite3_last_insert_rowid(x1),
      SP: x0 => ({create: x0}),
      SQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      SR: (x0,x1) => x0.replace(x1),
      SS: x0 => x0.videoWidth,
      ST: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      SU: (x0,x1) => { x0.exposureMode = x1 },
      SV: x0 => x0.x,
      SW: x0 => x0.height,
      SX: () => globalThis.google.maps.MapTypeId.HYBRID,
      SY: (x0,x1) => { x0.scaledSize = x1 },
      SZ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Sa: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      Sb: x0 => x0.state,
      Sc: x0 => x0.phoneNumber,
      Sd: () => new firebase_auth.PhoneAuthProvider(),
      Se: x0 => x0.path,
      Sf: x0 => globalThis.firebase_firestore.getDocsFromServer(x0),
      T: o => o instanceof RegExp,
      TB: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      TC: (x0,x1) => x0.getAttribute(x1),
      TD: (a, l) => a.length = l,
      TE: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      TF: () => globalThis.console,
      TG: x0 => x0.maxWidth,
      TH: (x0,x1) => { x0.type = x1 },
      TI: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      TJ: x0 => x0.naturalWidth,
      TK: x0 => x0.height,
      TL: x0 => x0.statusText,
      TM: x0 => x0.id,
      TN: () => Symbol("jsBoxedDartObjectProperty"),
      TO: x0 => globalThis.Number(x0),
      TP: (x0,x1,x2) => x0.getFileHandle(x1,x2),
      TQ: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2) { return wasmFunction(f,arguments.length,x0,x1,x2) }),
      TR: (x0,x1) => { x0.height = x1 },
      TS: x0 => x0.videoHeight,
      TT: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      TU: x0 => x0.exposureMode,
      TV: x0 => x0.bottomLeft,
      TW: x0 => x0.width,
      TX: () => globalThis.google.maps.MapTypeId.TERRAIN,
      TY: (x0,x1) => { x0.size = x1 },
      TZ: (x0,x1,x2) => ({enableHighAccuracy: x0,timeout: x1,maximumAge: x2}),
      Ta: () => globalThis.window.flutter_inappwebview,
      Tb: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Tc: x0 => x0.uid,
      Td: (x0,x1) => globalThis.firebase_auth.signInWithCustomToken(x0,x1),
      Te: (x0,x1,x2,x3) => x0.set(x1,x2,x3),
      Tf: x0 => globalThis.firebase_firestore.getDocsFromCache(x0),
      U: (string, times) => string.repeat(times),
      UB: x0 => new Float64Array(x0),
      UC: x0 => x0.remove(),
      UD: (x0,x1) => x0.closest(x1),
      UE: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      UF: s => s.trimRight(),
      UG: x0 => x0.minHeight,
      UH: (x0,x1) => { x0.className = x1 },
      UI: x0 => new WeakRef(x0),
      UJ: (x0,x1) => x0.createElement(x1),
      UK: x0 => x0.width,
      UL: x0 => x0.readyState,
      UM: (x0,x1,x2,x3) => ({method: x0,headers: x1,body: x2,credentials: x3}),
      UN: (x0,x1) => x0.call(x1),
      UO: (x0,x1,x2) => x0.sqlite3_column_name(x1,x2),
      UP: x0 => ({create: x0}),
      UQ: (x0,x1) => x0.getBigInt64(x1),
      UR: (x0,x1) => { x0.width = x1 },
      US: x0 => x0.duration,
      UT: (x0,x1,x2) => x0.getCurrentPosition(x1,x2),
      UU: (x0,x1) => { x0.focusMode = x1 },
      UV: x0 => x0.bottomRight,
      UW: (x0,x1) => { x0.src = x1 },
      UX: () => globalThis.google.maps.MapTypeId.SATELLITE,
      UY: (x0,x1) => new google.maps.Size(x0,x1),
      UZ: (x0,x1,x2,x3) => x0.getCurrentPosition(x1,x2,x3),
      Ua: (x0,x1) => { x0.csp = x1 },
      Ub: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Uc: x0 => x0.enrollmentTime,
      Ud: x0 => x0.signOut(),
      Ue: (x0,x1,x2) => x0.set(x1,x2),
      Uf: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      V: o => o,
      VB: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      VC: (x0,x1) => x0.appendChild(x1),
      VD: x0 => x0.bottom,
      VE: (o, i) => o[i],
      VF: x0 => x0.blur(),
      VG: x0 => x0.minWidth,
      VH: (x0,x1) => { x0.tabIndex = x1 },
      VI: x0 => x0.deref(),
      VJ: (x0,x1) => { x0.pointerEvents = x1 },
      VK: x0 => x0.userAgent,
      VL: () => globalThis.origin,
      VM: () => globalThis.window.navigator.userAgent,
      VN: x0 => x0.locks,
      VO: (x0,x1,x2) => x0.sqlite3_column_blob(x1,x2),
      VP: (x0,x1,x2) => x0.getDirectoryHandle(x1,x2),
      VQ: (x0,x1) => x0.getInt32(x1),
      VR: x0 => x0.cookie,
      VS: (x0,x1) => { x0.playsInline = x1 },
      VT: () => globalThis.Notification.requestPermission(),
      VU: x0 => x0.focusMode,
      VV: x0 => x0.topRight,
      VW: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24) => ({aspectRatio: x0,background: x1,center: x2,checkCrossOrigin: x3,checkOrientation: x4,cropBoxMovable: x5,cropBoxResizable: x6,dragMode: x7,guides: x8,highlight: x9,initialAspectRatio: x10,minContainerHeight: x11,minContainerWidth: x12,minCropBoxHeight: x13,minCropBoxWidth: x14,modal: x15,movable: x16,rotatable: x17,scalable: x18,toggleDragModeOnDblclick: x19,viewMode: x20,wheelZoomRatio: x21,zoomOnTouch: x22,zoomOnWheel: x23,zoomable: x24}),
      VX: () => ({}),
      VY: (x0,x1) => { x0.anchor = x1 },
      VZ: x0 => x0.message,
      Va: x0 => x0.csp,
      Vb: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      Vc: x0 => x0.factorId,
      Vd: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Ve: (x0,x1) => new firebase_firestore.Timestamp(x0,x1),
      Vf: (x0,x1) => x0.forEach(x1),
      W: o => {
        if (o === undefined || o === null) return 0;
        if (typeof o === 'boolean') return 1;
        return 2;
      },
      WB: x0 => new ArrayBuffer(x0),
      WC: (x0,x1) => x0.append(x1),
      WD: x0 => x0.top,
      WE: o => o.length,
      WF: x0 => x0.button,
      WG: x0 => x0.debugSkipFontRetryDelay,
      WH: (x0,x1) => { x0.name = x1 },
      WI: () => globalThis.WeakRef,
      WJ: (x0,x1) => { x0.height = x1 },
      WK: x0 => x0.navigator,
      WL: () => new XMLHttpRequest(),
      WM: x0 => x0.hostname,
      WN: () => globalThis.navigator,
      WO: (x0,x1,x2) => x0.sqlite3_column_bytes(x1,x2),
      WP: (x0,x1) => new URL(x0,x1),
      WQ: (x0,x1) => x0.read(x1),
      WR: x0 => x0.languages,
      WS: (x0,x1) => { x0.controls = x1 },
      WT: x0 => ({video: x0}),
      WU: x0 => x0.enumerateDevices(),
      WV: x0 => x0.topLeft,
      WW: () => ({}),
      WX: (x0,x1) => { x0.stylers = x1 },
      WY: x0 => x0.height,
      WZ: x0 => x0.code,
      Wa: (x0,x1) => { x0.name = x1 },
      Wb: (x0,x1,x2,x3,x4) => x0.on(x1,x2,x3,x4),
      Wc: x0 => x0.displayName,
      Wd: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      We: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      Wf: x0 => x0.source,
      X: x0 => x0.dotAll,
      XB: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      XC: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      XD: x0 => x0.right,
      XE: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      XF: x0 => x0.innerHeight,
      XG: x0 => x0.status,
      XH: (x0,x1) => { x0.placeholder = x1 },
      XI: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      XJ: (x0,x1) => { x0.width = x1 },
      XK: () => new FileReader(),
      XL: (x0,x1,x2) => x0.open(x1,x2),
      XM: x0 => x0.port,
      XN: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      XO: (x0,x1,x2) => x0.sqlite3_column_text(x1,x2),
      XP: x0 => x0.pathname,
      XQ: (x0,x1,x2) => x0.read(x1,x2),
      XR: x0 => x0.protocol,
      XS: (x0,x1) => { x0.autoplay = x1 },
      XT: (x0,x1) => x0.getUserMedia(x1),
      XU: x0 => x0.deviceId,
      XV: x0 => x0.position,
      XW: (x0,x1) => x0.getCroppedCanvas(x1),
      XX: (x0,x1) => { x0.featureType = x1 },
      XY: x0 => x0.width,
      XZ: x0 => x0.speed,
      Xa: x0 => x0.name,
      Xb: x0 => x0.snapshot,
      Xc: x0 => x0.hints,
      Xd: (x0,x1,x2) => x0.onIdTokenChanged(x1,x2),
      Xe: x0 => globalThis.firebase_firestore.increment(x0),
      Xf: x0 => ({source: x0}),
      Y: x0 => x0.unicode,
      YB: (x0,x1,x2) => new DataView(x0,x1,x2),
      YC: x0 => x0.style,
      YD: x0 => x0.left,
      YE: x0 => x0.language,
      YF: x0 => x0.innerWidth,
      YG: (x0,x1,x2) => x0.set(x1,x2),
      YH: (x0,x1) => { x0.autocomplete = x1 },
      YI: (a, s, e) => a.slice(s, e),
      YJ: x0 => x0.style,
      YK: (x0,x1) => x0.readAsArrayBuffer(x1),
      YL: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      YM: x0 => x0.protocol,
      YN: (x0,x1) => x0.postMessage(x1),
      YO: (x0,x1,x2) => x0.sqlite3_column_double(x1,x2),
      YP: x0 => x0.getDirectory(),
      YQ: x0 => x0.flush(),
      YR: () => globalThis.window.isSecureContext,
      YS: x0 => x0.currentTime,
      YT: x0 => x0.getVideoTracks(),
      YU: x0 => x0.kind,
      YV: x0 => x0.isValid,
      YW: x0 => x0.getCroppedCanvas(),
      YX: (x0,x1) => { x0.elementType = x1 },
      YY: (x0,x1) => { x0.url = x1 },
      YZ: x0 => x0.heading,
      Ya: (x0,x1) => { x0.referrerPolicy = x1 },
      Yb: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Yc: x0 => x0.tenantId,
      Yd: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Ye: x0 => ({merge: x0}),
      Yf: (x0,x1,x2) => globalThis.firebase_firestore.where(x0,x1,x2),
      Z: x0 => x0.ignoreCase,
      ZB: (o, p) => o[p],
      ZC: x0 => x0.debugShowSemanticsNodes,
      ZD: x0 => x0.clientY,
      ZE: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      ZF: x0 => x0.height,
      ZG: x0 => x0.arrayBuffer(),
      ZH: (x0,x1) => { x0.name = x1 },
      ZI: () => new AbortController(),
      ZJ: (x0,x1) => { x0.src = x1 },
      ZK: x0 => x0.result,
      ZL: (x0,x1) => { x0.withCredentials = x1 },
      ZM: x0 => x0.location,
      ZN: x0 => x0.close(),
      ZO: (x0,x1,x2) => x0.sqlite3_column_int64(x1,x2),
      ZP: x0 => x0.storage,
      ZQ: () => globalThis.WebAssembly,
      ZR: () => globalThis.crypto.subtle,
      ZS: (x0,x1) => { x0.playbackRate = x1 },
      ZT: x0 => x0.stop(),
      ZU: x0 => x0.facingMode,
      ZV: (x0,x1,x2,x3) => ({formats: x0,tryHarder: x1,tryRotate: x2,tryInvert: x3}),
      ZW: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      ZX: (x0,x1,x2,x3,x4,x5,x6,x7) => ({hue: x0,lightness: x1,saturation: x2,gamma: x3,invert_lightness: x4,visibility: x5,color: x6,weight: x7}),
      ZY: (x0,x1) => { x0.position = x1 },
      ZZ: x0 => x0.accuracy,
      Za: x0 => x0.referrerPolicy,
      Zb: (x0,x1) => x0.then(x1),
      Zc: x0 => x0.phoneNumber,
      Zd: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      Ze: x0 => new firebase_firestore.FieldPath(x0),
      Zf: (x0,x1) => globalThis.firebase_firestore.query(x0,x1),
      a: x0 => x0.multiline,
      aB: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      aC: (x0,x1) => x0.warn(x1),
      aD: x0 => x0.clientX,
      aE: () => globalThis.window.FinalizationRegistry,
      aF: x0 => x0.width,
      aG: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof ArrayBuffer) return 1;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 2;
        }
        return 3;
      },
      aH: (x0,x1) => { x0.placeholder = x1 },
      aI: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      aJ: () => globalThis.document,
      aK: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      aL: (x0,x1) => { x0.responseType = x1 },
      aM: (x0,x1) => x0.getResponseHeader(x1),
      aN: (x0,x1) => ({i: x0,p: x1}),
      aO: (x0,x1,x2) => x0.sqlite3_column_type(x1,x2),
      aP: () => globalThis.navigator,
      aQ: x0 => x0.href,
      aR: (d, precision) => d.toPrecision(precision),
      aS: x0 => x0.pause(),
      aT: x0 => x0.active,
      aU: x0 => x0.mediaDevices,
      aV: (x0,x1,x2) => ({tryHarder: x0,tryRotate: x1,tryInvert: x2}),
      aW: (x0,x1,x2) => x0.toBlob(x1,x2),
      aX: (x0,x1) => x0.clearMarkers(x1),
      aY: x0 => new google.maps.InfoWindow(x0),
      aZ: x0 => x0.altitudeAccuracy,
      aa: (x0,x1) => { x0.allowFullscreen = x1 },
      ab: (x0,x1,x2) => globalThis.firebase_storage.uploadBytesResumable(x0,x1,x2),
      ac: x0 => x0.email,
      ad: (x0,x1,x2) => x0.onAuthStateChanged(x1,x2),
      ae: (x0,x1) => new firebase_firestore.FieldPath(x0,x1),
      af: () => globalThis.firebase_firestore.and,
      b: (exn) => {
        if (exn instanceof Error) {
          return exn.stack;
        } else {
          return null;
        }
      },
      bB: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      bC: x0 => x0.console,
      bD: x0 => x0.changedTouches,
      bE: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      bF: x0 => x0.clientHeight,
      bG: (x0,x1) => x0.fetch(x1),
      bH: (x0,x1) => { x0.action = x1 },
      bI: (x0,x1) => globalThis.fetch(x0,x1),
      bJ: x0 => x0.src,
      bK: x0 => x0.type,
      bL: (x0,x1) => { x0.innerHTML = x1 },
      bM: x0 => x0.responseText,
      bN: (x0,x1) => ({c: x0,r: x1}),
      bO: (x0,x1) => x0.sqlite3_column_count(x1),
      bP: (x0,x1) => globalThis.fetch(x0,x1),
      bQ: (x0,x1) => x0.openCursor(x1),
      bR: (x0,x1) => x0.getItem(x1),
      bS: x0 => x0.play(),
      bT: x0 => ({audio: x0}),
      bU: () => globalThis.BarcodeDetector.getSupportedFormats(),
      bV: () => globalThis.ZXingWASM,
      bW: (x0,x1) => { x0.fillColor = x1 },
      bX: x0 => x0.onRemove(),
      bY: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      bZ: x0 => x0.altitude,
      ba: x0 => x0.allowFullscreen,
      bb: () => ({}),
      bc: (x0,x1) => globalThis.firebase_auth.getMultiFactorResolver(x0,x1),
      bd: x0 => x0.tenantId,
      be: (x0,x1,x2) => new firebase_firestore.FieldPath(x0,x1,x2),
      bf: () => globalThis.firebase_firestore.or,
      c: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      cB: o => o.byteOffset,
      cC: () => globalThis.window,
      cD: x0 => x0.offsetY,
      cE: x0 => new window.FinalizationRegistry(x0),
      cF: x0 => x0.clientWidth,
      cG: x0 => x0.fontFallbackBaseUrl,
      cH: (x0,x1) => { x0.method = x1 },
      cI: (x0,x1) => x0.get(x1),
      cJ: (x0,x1) => x0.revokeObjectURL(x1),
      cK: x0 => x0.vendor,
      cL: (x0,x1) => { x0.width = x1 },
      cM: (x0,x1,x2) => x0.close(x1,x2),
      cN: (x0,x1) => { x0.onmessage = x1 },
      cO: (x0,x1) => x0.sqlite3_close_v2(x1),
      cP: (x0,x1) => x0.sqlite3session_delete(x1),
      cQ: () => globalThis.Blob,
      cR: (x0,x1,x2) => x0.setItem(x1,x2),
      cS: x0 => x0.message,
      cT: x0 => x0.getAudioTracks(),
      cU: x0 => x0.reset,
      cV: x0 => x0.height,
      cW: (x0,x1) => { x0.maxHeight = x1 },
      cX: x0 => x0.onAdd(),
      cY: (x0,x1) => { x0.onclick = x1 },
      cZ: x0 => x0.timestamp,
      ca: x0 => x0.allow,
      cb: (x0,x1) => { x0.customMetadata = x1 },
      cc: x0 => x0.customData,
      cd: x0 => x0.currentUser,
      ce: (x0,x1,x2,x3) => new firebase_firestore.FieldPath(x0,x1,x2,x3),
      cf: x0 => globalThis.firebase_firestore.limitToLast(x0),
      d: (x0,x1) => x0.didCreateEngineInitializer(x1),
      dB: o => o.buffer,
      dC: (o, c) => o instanceof c,
      dD: x0 => x0.offsetX,
      dE: (x0,x1) => x0.unregister(x1),
      dF: (x0,x1) => { x0.content = x1 },
      dG: (handle) => clearInterval(handle),
      dH: (x0,x1) => { x0.noValidate = x1 },
      dI: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2) { return wasmFunction(f,arguments.length,x0,x1,x2) }),
      dJ: (x0,x1) => { x0.src = x1 },
      dK: x0 => x0.size,
      dL: (x0,x1) => { x0.height = x1 },
      dM: x0 => x0.close(),
      dN: (o, a) => o == a,
      dO: (x0,x1,x2,x3,x4,x5,x6) => x0.dart_sqlite3_create_function_v2(x1,x2,x3,x4,x5,x6),
      dP: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      dQ: x0 => x0.value,
      dR: x0 => x0.localStorage,
      dS: (x0,x1) => { x0.currentTime = x1 },
      dT: x0 => ({name: x0}),
      dU: x0 => x0.stopContinuousDecode,
      dV: x0 => x0.width,
      dW: (x0,x1) => { x0.maxWidth = x1 },
      dX: x0 => new markerClusterer.MarkerClusterer(x0),
      dY: (x0,x1,x2) => x0.addMarkers(x1,x2),
      dZ: x0 => x0.longitude,
      da: x0 => x0.src,
      db: (x0,x1) => { x0.contentType = x1 },
      dc: x0 => x0.message,
      dd: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      de: (x0,x1,x2,x3,x4) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4),
      df: x0 => globalThis.firebase_firestore.limit(x0),
      e: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      eB: Function.prototype.call.bind(DataView.prototype.getUint8),
      eC: (x0,x1) => x0[x1],
      eD: x0 => x0.type,
      eE: (x0,x1) => x0.contains(x1),
      eF: (x0,x1) => { x0.name = x1 },
      eG: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      eH: (x0,x1) => x0.removeAttribute(x1),
      eI: (x0,x1) => x0.forEach(x1),
      eJ: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      eK: x0 => x0.decode(),
      eL: (x0,x1) => { x0.border = x1 },
      eM: () => new Array(),
      eN: x0 => x0.r,
      eO: (x0,x1,x2,x3) => x0.sqlite3_result_error(x1,x2,x3),
      eP: (x0,x1) => x0.unregister(x1),
      eQ: x0 => x0.key,
      eR: () => globalThis.loadFirebaseConfig(),
      eS: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      eT: (x0,x1) => x0.query(x1),
      eU: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      eV: (x0,x1) => { x0.srcObject = x1 },
      eW: (x0,x1) => x0.scale(x1),
      eX: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2) { return wasmFunction(f,arguments.length,x0,x1,x2) }),
      eY: () => ({}),
      eZ: x0 => x0.latitude,
      ea: (x0,x1) => x0.item(x1),
      eb: x0 => globalThis.firebase_storage.getDownloadURL(x0),
      ec: x0 => x0.code,
      ed: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      ee: (x0,x1,x2,x3,x4,x5) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5),
      ef: () => globalThis.firebase_firestore.endBefore,
      f: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      fB: (b, o) => new DataView(b, o),
      fC: x0 => x0.length,
      fD: x0 => x0.maxTouchPoints,
      fE: (s) => +s,
      fF: x0 => x0.head,
      fG: () => Date.now(),
      fH: x0 => x0.isConnected,
      fI: x0 => x0.name,
      fJ: x0 => x0.naturalHeight,
      fK: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      fL: x0 => x0.style,
      fM: (x0,x1) => new WebSocket(x0,x1),
      fN: x0 => x0.c,
      fO: (x0,x1,x2) => x0.sqlite3_result_subtype(x1,x2),
      fP: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      fQ: x0 => x0.continue(),
      fR: x0 => x0.measurementId,
      fS: (x0,x1,x2) => x0.setAttribute(x1,x2),
      fT: x0 => x0.state,
      fU: (x0,x1,x2,x3) => x0.call(x1,x2,x3),
      fV: x0 => ({willReadFrequently: x0}),
      fW: (x0,x1) => x0.rotate(x1),
      fX: (x0,x1,x2) => ({map: x0,markers: x1,onClusterClick: x2}),
      fY: (x0,x1) => x0.removeAt(x1),
      fZ: x0 => x0.coords,
      fa: x0 => x0.length,
      fb: x0 => globalThis.firebase_remote_config.ensureInitialized(x0),
      fc: x0 => x0.idToken,
      fd: (x0,x1) => globalThis.firebase_auth.connectAuthEmulator(x0,x1),
      fe: (x0,x1,x2,x3,x4,x5,x6) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6),
      ff: () => globalThis.firebase_firestore.endAt,
      g: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      gB: (b, o, l) => new DataView(b, o, l),
      gC: (string, token) => string.split(token),
      gD: x0 => x0.platform,
      gE: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      gF: (x0,x1) => x0.removeChild(x1),
      gG: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      gH: x0 => x0.click(),
      gI: x0 => x0.statusText,
      gJ: x0 => x0.naturalWidth,
      gK: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      gL: x0 => x0.userAgent,
      gM: x0 => x0.reason,
      gN: x0 => x0.p,
      gO: (x0,x1,x2,x3,x4) => x0.sqlite3_result_blob64(x1,x2,x3,x4),
      gP: x0 => new FinalizationRegistry(x0),
      gQ: x0 => x0.error,
      gR: x0 => x0.storageBucket,
      gS: (x0,x1) => { x0.cursor = x1 },
      gT: x0 => x0.permissions,
      gU: x0 => x0.text,
      gV: () => new BarcodeDetector(),
      gW: (x0,x1) => new Cropper(x0,x1),
      gX: x0 => x0.render(),
      gY: x0 => x0.overlayMapTypes,
      gZ: x0 => globalThis.Intl.supportedValuesOf(x0),
      ga: x0 => x0.sandbox,
      gb: x0 => globalThis.firebase_remote_config.getRemoteConfig(x0),
      gc: x0 => x0.secret,
      gd: x0 => globalThis.firebase_installations.getId(x0),
      ge: (x0,x1,x2,x3,x4,x5,x6,x7) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7),
      gf: () => globalThis.firebase_firestore.startAfter,
      h: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      hB: Function.prototype.call.bind(DataView.prototype.getFloat64),
      hC: o => o instanceof Array,
      hD: x0 => x0.body,
      hE: s => s.trim(),
      hF: x0 => x0.firstChild,
      hG: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      hH: (x0,x1) => x0.getElementsByClassName(x1),
      hI: x0 => x0.url,
      hJ: x0 => x0.decode(),
      hK: (x0,x1,x2) => x0.addEventListener(x1,x2),
      hL: () => globalThis.navigator,
      hM: x0 => x0.code,
      hN: x0 => x0.i,
      hO: (x0,x1,x2,x3,x4) => x0.sqlite3_result_text(x1,x2,x3,x4),
      hP: () => globalThis.FinalizationRegistry,
      hQ: x0 => x0.result,
      hR: x0 => x0.messagingSenderId,
      hS: (x0,x1) => { x0.display = x1 },
      hT: x0 => x0.geolocation,
      hU: x0 => x0.barcodeFormat,
      hV: x0 => ({formats: x0}),
      hW: (x0,x1) => { x0.maxWidth = x1 },
      hX: (x0,x1,x2) => x0.removeMarkers(x1,x2),
      hY: x0 => x0.remove(),
      hZ: () => globalThis.Intl.DateTimeFormat(),
      ha: (x0,x1) => x0.getCookieExpirationDate(x1),
      hb: x0 => x0.measurementId,
      hc: x0 => x0.accessToken,
      hd: x0 => globalThis.firebase_installations.getInstallations(x0),
      he: (x0,x1,x2,x3,x4,x5,x6,x7,x8) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8),
      hf: () => globalThis.firebase_firestore.startAt,
      i: x0 => new Promise(x0),
      iB: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Float64Array) return 1;
        return 2;
      },
      iC: (a, i, v) => a[i] = v,
      iD: () => globalThis.document,
      iE: x0 => x0.classList,
      iF: x0 => x0.viewConstraints,
      iG: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      iH: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      iI: x0 => x0.status,
      iJ: (x0,x1) => { x0.decoding = x1 },
      iK: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      iL: x0 => x0.exitFullscreen(),
      iM: x0 => x0.readyState,
      iN: x0 => x0.port1,
      iO: (x0,x1,x2) => x0.sqlite3_result_double(x1,x2),
      iP: (x0,x1) => x0.sqlite3changeset_finalize(x1),
      iQ: (x0,x1) => globalThis.IDBKeyRange.bound(x0,x1),
      iR: x0 => x0.appId,
      iS: (x0,x1) => { x0.opacity = x1 },
      iT: x0 => x0.mediaDevices,
      iU: x0 => x0.rawBytes,
      iV: x0 => new BarcodeDetector(x0),
      iW: x0 => x0.getNorthEast(),
      iX: (x0,x1) => x0.setContent(x1),
      iY: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      iZ: x0 => x0.resolvedOptions(),
      ia: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      ib: x0 => x0.appId,
      ic: x0 => x0.signInMethod,
      id: (x0,x1) => globalThis.firebase_installations.getToken(x0,x1),
      ie: (x0,x1,x2,x3,x4,x5,x6,x7,x8,x9) => new firebase_firestore.FieldPath(x0,x1,x2,x3,x4,x5,x6,x7,x8,x9),
      if: (x0,x1) => globalThis.firebase_firestore.orderBy(x0,x1),
      j: (x0,x1,x2) => x0.call(x1,x2),
      jB: Function.prototype.call.bind(DataView.prototype.setFloat64),
      jC: (a, i) => a[i],
      jD: (x0,x1,x2) => x0.addEventListener(x1,x2),
      jE: x0 => x0.preventDefault(),
      jF: x0 => x0.hostElement,
      jG: o => o.byteLength,
      jH: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      jI: x0 => x0.getReader(),
      jJ: (x0,x1) => { x0.crossOrigin = x1 },
      jK: x0 => x0.send(),
      jL: x0 => x0.fullscreenElement,
      jM: (x0,x1) => { x0.binaryType = x1 },
      jN: (x0,x1,x2) => x0.transaction(x1,x2),
      jO: (x0,x1,x2) => x0.sqlite3_result_int64(x1,x2),
      jP: x0 => x0.exports,
      jQ: x0 => x0.length,
      jR: x0 => x0.projectId,
      jS: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      jT: x0 => x0.height,
      jU: x0 => x0.y,
      jV: (x0,x1) => x0.detect(x1),
      jW: x0 => x0.lng(),
      jX: (x0,x1) => { x0.zIndex = x1 },
      jY: (x0,x1,x2) => globalThis.google.maps.event.addListener(x0,x1,x2),
      jZ: x0 => x0.timeZone,
      ja: (x0,x1) => globalThis.branch.link(x0,x1),
      jb: x0 => x0.messagingSenderId,
      jc: x0 => x0.providerId,
      jd: x0 => x0.token,
      je: () => globalThis.firebase_firestore.documentId(),
      jf: x0 => x0.id,
      k: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      kB: Function.prototype.call.bind(DataView.prototype.setUint8),
      kC: a => a.length,
      kD: x0 => x0.hasFocus(),
      kE: x0 => x0.parent,
      kF: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      kG: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      kH: (x0,x1) => x0.dispatchEvent(x1),
      kI: x0 => x0.read(),
      kJ: (x0,x1) => x0.createObjectURL(x1),
      kK: x0 => x0.status,
      kL: x0 => x0.requestFullscreen(),
      kM: (x0,x1) => x0.send(x1),
      kN: x0 => x0.close(),
      kO: (x0,x1) => x0.sqlite3_result_null(x1),
      kP: x0 => x0.call(),
      kQ: (x0,x1) => x0.get(x1),
      kR: x0 => x0.authDomain,
      kS: x0 => x0.preventDefault(),
      kT: x0 => x0.pageNumber,
      kU: x0 => x0.x,
      kV: x0 => x0.rawValue,
      kW: x0 => x0.lat(),
      kX: x0 => x0.zIndex,
      kY: x0 => x0.getTilt(),
      kZ: (x0,x1,x2,x3) => x0.decrypt(x1,x2,x3),
      ka: x0 => globalThis.JSON.parse(x0),
      kb: x0 => x0.authDomain,
      kc: (x0,x1) => globalThis.firebase_auth.applyActionCode(x0,x1),
      kd: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      ke: (x0,x1) => new firebase_firestore.GeoPoint(x0,x1),
      kf: x0 => x0.path,
      l: x0 => new Array(x0),
      lB: (t, s) => t.set(s),
      lC: (x0,x1) => x0.test(x1),
      lD: x0 => x0.relatedTarget,
      lE: x0 => x0.timeStamp,
      lF: x0 => ({runApp: x0}),
      lG: x0 => x0.history,
      lH: (x0,x1) => x0.createEvent(x1),
      lI: x0 => x0.value,
      lJ: x0 => x0.URL,
      lK: x0 => x0.response,
      lL: x0 => x0.documentElement,
      lM: (x0,x1,x2,x3) => x0.putImageData(x1,x2,x3),
      lN: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      lO: (x0,x1) => x0.sqlite3_value_blob(x1),
      lP: x0 => x0.instance,
      lQ: (x0,x1) => x0.index(x1),
      lR: x0 => x0.apiKey,
      lS: x0 => x0.shiftKey,
      lT: (x0,x1) => x0.getPage(x1),
      lU: x0 => x0.resultPoints,
      lV: x0 => x0.format,
      lW: x0 => x0.getSouthWest(),
      lX: (x0,x1) => { x0.title = x1 },
      lY: x0 => x0.getHeading(),
      lZ: x0 => x0.subtle,
      la: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      lb: x0 => x0.projectId,
      lc: x0 => x0.reload(),
      ld: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      le: x0 => globalThis.firebase_firestore.vector(x0),
      lf: x0 => globalThis.firebase_firestore.doc(x0),
      m: o => [o],
      mB: Function.prototype.call.bind(DataView.prototype.setFloat32),
      mC: x0 => x0.userAgent,
      mD: x0 => x0.shiftKey,
      mE: (x0,x1) => x0.hasAttribute(x1),
      mF: () => typeof dartUseDateNowForTicks !== "undefined",
      mG: x0 => x0.search,
      mH: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      mI: x0 => x0.done,
      mJ: x0 => new Blob(x0),
      mK: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      mL: x0 => x0.webkitExitFullscreen(),
      mM: x0 => x0.arrayBuffer(),
      mN: () => globalThis.Promise.resolve(),
      mO: (x0,x1) => x0.sqlite3_value_bytes(x1),
      mP: (x0,x1,x2) => x0.instantiateStreaming(x1,x2),
      mQ: x0 => x0.openKeyCursor(),
      mR: x0 => x0.arrayBuffer(),
      mS: x0 => x0.metaKey,
      mT: (x0,x1,x2,x3) => ({cMapUrl: x0,cMapPacked: x1,data: x2,password: x3}),
      mU: x0 => x0.message,
      mV: x0 => x0.y,
      mW: (x0,x1) => new google.maps.LatLngBounds(x0,x1),
      mX: x0 => x0.title,
      mY: x0 => x0.getCenter(),
      mZ: x0 => x0.crypto,
      ma: x0 => globalThis.branch.data(x0),
      mb: x0 => x0.name,
      mc: (x0,x1) => globalThis.firebase_auth.reauthenticateWithCredential(x0,x1),
      md: (x0,x1,x2) => globalThis.firebase_app_check.onTokenChanged(x0,x1,x2),
      me: x0 => globalThis.firebase_firestore.Bytes.fromUint8Array(x0),
      mf: (x0,x1) => ({includeMetadataChanges: x0,source: x1}),
      n: (o0, o1) => [o0, o1],
      nB: Function.prototype.call.bind(DataView.prototype.getFloat32),
      nC: x0 => x0.navigator,
      nD: (decoder, codeUnits) => decoder.decode(codeUnits),
      nE: x0 => x0.buttons,
      nF: () => Date.now(),
      nG: x0 => x0.location,
      nH: x0 => x0.readText(),
      nI: x0 => x0.cancel(),
      nJ: x0 => x0.close(),
      nK: (x0,x1) => { x0.responseType = x1 },
      nL: x0 => x0.webkitDisplayingFullscreen,
      nM: (x0,x1) => x0.transferFromImageBitmap(x1),
      nN: (x0,x1) => x0.then(x1),
      nO: (x0,x1) => x0.sqlite3_value_text(x1),
      nP: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      nQ: x0 => x0.primaryKey,
      nR: (x0,x1) => x0.removeItem(x1),
      nS: x0 => x0.altKey,
      nT: (x0,x1) => x0.getDocument(x1),
      nU: x0 => x0.videoElement,
      nV: x0 => x0.x,
      nW: (x0,x1) => new google.maps.LatLng(x0,x1),
      nX: (x0,x1) => { x0.position = x1 },
      nY: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      nZ: x0 => x0.isSecureContext,
      na: x0 => globalThis.JSON.stringify(x0),
      nb: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      nc: (x0,x1) => globalThis.firebase_auth.PhoneAuthProvider.credential(x0,x1),
      nd: x0 => new firebase_app_check.ReCaptchaV3Provider(x0),
      ne: x0 => x0.commit(),
      nf: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      o: (o0, o1, o2) => [o0, o1, o2],
      oB: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Float32Array) return 1;
        return 2;
      },
      oC: Function.prototype.call.bind(String.prototype.toLowerCase),
      oD: () => new TextDecoder("utf-8", {fatal: true}),
      oE: x0 => x0.ctrlKey,
      oF: () => 1000 * performance.now(),
      oG: x0 => x0.pathname,
      oH: x0 => x0.clipboard,
      oI: x0 => x0.body,
      oJ: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      oK: () => new XMLHttpRequest(),
      oL: (x0,x1) => x0.getElementById(x1),
      oM: x0 => x0.height,
      oN: x0 => x0.abort(),
      oO: (x0,x1) => x0.sqlite3_value_double(x1),
      oP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      oQ: (x0,x1,x2) => x0.open(x1,x2),
      oR: x0 => x0.href,
      oS: x0 => x0.ctrlKey,
      oT: x0 => x0.promise,
      oU: x0 => x0.decodeContinuously,
      oV: x0 => x0.cornerPoints,
      oW: x0 => x0.getBounds(),
      oX: x0 => x0.position,
      oY: x0 => x0.latLng,
      oZ: (x0,x1,x2,x3,x4,x5,x6,x7) => x0.unwrapKey(x1,x2,x3,x4,x5,x6,x7),
      oa: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      ob: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      oc: (x0,x1) => globalThis.firebase_auth.updatePhoneNumber(x0,x1),
      od: x0 => new firebase_app_check.ReCaptchaEnterpriseProvider(x0),
      oe: x0 => globalThis.firebase_firestore.writeBatch(x0),
      of: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      p: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      pB: Function.prototype.call.bind(DataView.prototype.setUint32),
      pC: Object.is,
      pD: () => new TextDecoder("utf-8", {fatal: false}),
      pE: x0 => x0.y,
      pF: (x0,x1) => x0.requestAnimationFrame(x1),
      pG: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      pH: (x0,x1) => x0.writeText(x1),
      pI: x0 => x0.headers,
      pJ: (x0,x1) => x0.decode(x1),
      pK: x0 => x0.data,
      pL: x0 => x0.webkitEnterFullscreen(),
      pM: x0 => x0.width,
      pN: x0 => x0.commit(),
      pO: (x0,x1) => x0.sqlite3_value_int64(x1),
      pP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3,x4) { return wasmFunction(f,arguments.length,x0,x1,x2,x3,x4) }),
      pQ: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      pR: x0 => x0.sessionStorage,
      pS: (x0,x1) => x0.getAttribute(x1),
      pT: x0 => x0.cMapPacked,
      pU: (x0,x1) => new ZXing.BrowserMultiFormatReader(x0,x1),
      pV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      pW: x0 => x0.getZoom(),
      pX: (x0,x1) => { x0.gmpDraggable = x1 },
      pY: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      pZ: (x0,x1,x2,x3,x4,x5) => x0.importKey(x1,x2,x3,x4,x5),
      pa: (x0,x1) => globalThis.branch.setIdentity(x0,x1),
      pb: x0 => globalThis.firebase_core.initializeApp(x0),
      pc: (x0,x1) => x0.getIdToken(x1),
      pd: x0 => ({provider: x0}),
      pe: (x0,x1) => globalThis.firebase_firestore.getFirestore(x0,x1),
      pf: (x0,x1,x2,x3) => globalThis.firebase_firestore.onSnapshot(x0,x1,x2,x3),
      q: (x0,x1,x2) => { x0[x1] = x2 },
      qB: Function.prototype.call.bind(DataView.prototype.getUint32),
      qC: x0 => x0.vendor,
      qD: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      qE: x0 => x0.x,
      qF: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      qG: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      qH: x0 => x0.unlock(),
      qI: x0 => x0.signal,
      qJ: x0 => x0.displayHeight,
      qK: x0 => x0.height,
      qL: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      qM: x0 => x0.rasterEndMilliseconds,
      qN: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      qO: (x0,x1) => x0.sqlite3_value_type(x1),
      qP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2) { return wasmFunction(f,arguments.length,x0,x1,x2) }),
      qQ: (x0,x1) => { x0.onupgradeneeded = x1 },
      qR: () => globalThis.loadProjectConfig(),
      qS: (x0,x1) => x0.closest(x1),
      qT: x0 => x0.cMapUrl,
      qU: (x0,x1) => ({width: x0,height: x1}),
      qV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      qW: (x0,x1) => x0.panTo(x1),
      qX: x0 => x0.gmpDraggable,
      qY: x0 => x0.latLng,
      qZ: (x0,x1,x2,x3) => x0.generateKey(x1,x2,x3),
      qa: x0 => x0.message,
      qb: x0 => x0.storageBucket,
      qc: x0 => x0.providerId,
      qd: (x0,x1) => globalThis.firebase_app_check.initializeAppCheck(x0,x1),
      qe: (x0,x1,x2) => globalThis.firebase_firestore.setDoc(x0,x1,x2),
      qf: (x0,x1) => globalThis.firebase_firestore.collection(x0,x1),
      r: (o, p) => o[p],
      rB: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Uint32Array) return 1;
        return 2;
      },
      rC: (x0,x1) => x0.createTextNode(x1),
      rD: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      rE: x0 => x0.scrollTop,
      rF: x0 => x0.now(),
      rG: o => Object.keys(o),
      rH: (x0,x1) => x0.lock(x1),
      rI: x0 => x0.abort(),
      rJ: x0 => x0.displayWidth,
      rK: x0 => x0.width,
      rL: (x0,x1,x2) => x0.addEventListener(x1,x2),
      rM: x0 => x0.rasterStartMilliseconds,
      rN: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      rO: (x0,x1,x2) => x0.sqlite3_extended_result_codes(x1,x2),
      rP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return wasmFunction(f,arguments.length,x0,x1,x2,x3) }),
      rQ: x0 => ({autoIncrement: x0}),
      rR: x0 => x0.environment,
      rS: x0 => x0.tagName,
      rT: (x0,x1) => ({cMapUrl: x0,cMapPacked: x1}),
      rU: (x0,x1,x2) => ({width: x0,height: x1,facingMode: x2}),
      rV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      rW: (x0,x1,x2) => x0.fitBounds(x1,x2),
      rX: (x0,x1) => { x0.content = x1 },
      rY: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      rZ: (x0,x1,x2,x3,x4) => x0.wrapKey(x1,x2,x3,x4),
      ra: x0 => x0.code,
      rb: x0 => x0.databaseURL,
      rc: x0 => x0.uid,
      rd: (x0,x1,x2) => globalThis.firebase_analytics.setUserId(x0,x1,x2),
      re: (x0,x1) => globalThis.firebase_firestore.setDoc(x0,x1),
      rf: x0 => x0.length,
      s: () => globalThis,
      sB: Function.prototype.call.bind(DataView.prototype.setInt32),
      sC: (x0,x1) => { x0.id = x1 },
      sD: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      sE: x0 => x0.offsetTop,
      sF: x0 => x0.performance,
      sG: x0 => x0.state,
      sH: x0 => x0.orientation,
      sI: x0 => x0.length,
      sJ: x0 => x0.duration,
      sK: x0 => x0.id,
      sL: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      sM: x0 => x0.imageBitmaps,
      sN: (x0,x1) => { x0.onerror = x1 },
      sO: (x0,x1,x2,x3,x4) => x0.sqlite3_open_v2(x1,x2,x3,x4),
      sP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return wasmFunction(f,arguments.length,x0,x1,x2,x3) }),
      sQ: (x0,x1,x2) => x0.createObjectStore(x1,x2),
      sR: x0 => x0.canvasKitMaximumSurfaces,
      sS: x0 => x0.target,
      sT: () => globalThis.pdfRenderOptions,
      sU: x0 => x0.facingMode,
      sV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      sW: (x0,x1,x2) => x0.panBy(x1,x2),
      sX: x0 => x0.content,
      sY: (wasmFunction,f) => finalizeWrapper(f, function() { return wasmFunction(f,arguments.length) }),
      sZ: (x0,x1,x2) => x0.exportKey(x1,x2),
      sa: (x0,x1) => globalThis.firebase_storage.ref(x0,x1),
      sb: x0 => x0.apiKey,
      sc: x0 => x0.providerData,
      sd: (x0,x1) => globalThis.firebase_analytics.initializeAnalytics(x0,x1),
      se: x0 => x0.fromCache,
      sf: x0 => x0.getReader(),
      t: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      tB: Function.prototype.call.bind(DataView.prototype.getInt32),
      tC: (x0,x1) => { x0.nonce = x1 },
      tD: x0 => x0.visibilityState,
      tE: x0 => x0.scrollLeft,
      tF: x0 => new Uint8Array(x0),
      tG: x0 => x0.hash,
      tH: (x0,x1) => x0.querySelector(x1),
      tI: x0 => x0.history,
      tJ: x0 => x0.image,
      tK: x0 => ({scale: x0}),
      tL: (o, p) => p in o,
      tM: (x0,x1) => { x0.height = x1 },
      tN: x0 => new DOMException(x0),
      tO: x0 => x0.sqlite3_initialize(),
      tP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2) { return wasmFunction(f,arguments.length,x0,x1,x2) }),
      tQ: x0 => ({unique: x0}),
      tR: x0 => x0.nextSibling,
      tS: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      tT: () => globalThis.pdfjsLib,
      tU: x0 => x0.height,
      tV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      tW: (x0,x1) => new google.maps.Point(x0,x1),
      tX: (x0,x1) => { x0.collisionBehavior = x1 },
      tY: (x0,x1) => new google.maps.Map(x0,x1),
      tZ: (x0,x1) => x0.getRandomValues(x1),
      ta: x0 => x0.name,
      tb: x0 => x0.options,
      tc: x0 => x0.tenantId,
      td: (x0,x1,x2,x3) => globalThis.firebase_analytics.logEvent(x0,x1,x2,x3),
      te: x0 => x0.hasPendingWrites,
      tf: x0 => x0.value,
      u: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      uB: o => {
        if (o === null || o === undefined) return 0;
        if (o instanceof Int32Array) return 1;
        return 2;
      },
      uC: x0 => x0.nonce,
      uD: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      uE: x0 => x0.offsetLeft,
      uF: (x0,x1,x2) => x0.slice(x1,x2),
      uG: x0 => x0.state,
      uH: (x0,x1) => { x0.title = x1 },
      uI: () => globalThis.window,
      uJ: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      uK: (x0,x1) => x0.getViewport(x1),
      uL: x0 => x0.groups,
      uM: (x0,x1) => { x0.width = x1 },
      uN: x0 => x0.error,
      uO: (x0,x1,x2,x3) => x0.dart_sqlite3_register_vfs(x1,x2,x3),
      uP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      uQ: (x0,x1,x2,x3) => x0.createIndex(x1,x2,x3),
      uR: (x0,x1) => x0.debug(x1),
      uS: (x0,x1) => x0.key(x1),
      uT: x0 => x0.baseURI,
      uU: x0 => x0.width,
      uV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      uW: (x0,x1,x2) => x0.fromPointToLatLng(x1,x2),
      uX: x0 => x0.collisionBehavior,
      uY: (x0,x1) => { x0.tilt = x1 },
      uZ: (x0,x1,x2,x3) => x0.encrypt(x1,x2,x3),
      ua: (x0,x1) => globalThis.firebase_storage.getStorage(x0,x1),
      ub: () => globalThis.firebase_core.SDK_VERSION,
      uc: x0 => x0.refreshToken,
      ud: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      ue: x0 => x0.metadata,
      uf: x0 => x0.done,
      v: (x0,x1) => ({addView: x0,removeView: x1}),
      vB: o => o instanceof Uint16Array,
      vC: () => globalThis.window.flutterConfiguration,
      vD: x0 => x0.disconnect(),
      vE: x0 => x0.offsetParent,
      vF: (x0,x1) => x0.decode(x1),
      vG: (x0,x1) => x0.go(x1),
      vH: (x0,x1) => x0.vibrate(x1),
      vI: () => new XMLHttpRequest(),
      vJ: x0 => new window.ImageDecoder(x0),
      vK: (x0,x1,x2,x3) => ({scale: x0,offsetX: x1,offsetY: x2,dontFlip: x3}),
      vL: (x0,x1) => x0.fetch(x1),
      vM: x0 => x0.convertToBlob(),
      vN: (x0,x1) => { x0.onabort = x1 },
      vO: (x0,x1) => globalThis.Atomics.load(x0,x1),
      vP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      vQ: (x0,x1) => x0.createObjectStore(x1),
      vR: x0 => x0.hostElement,
      vS: x0 => x0.length,
      vT: x0 => x0.document,
      vU: x0 => x0.attachStreamToVideo,
      vV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      vW: x0 => x0.y,
      vX: x0 => x0.content,
      vY: x0 => x0.rotateControl,
      vZ: (x0,x1) => { x0.text = x1 },
      va: x0 => globalThis.firebase_storage.getStorage(x0),
      vb: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      vc: x0 => x0.photoURL,
      vd: x0 => x0.message,
      ve: x0 => ({serverTimestamps: x0}),
      vf: x0 => x0.read(),
      w: (l, r) => l === r,
      wB: Function.prototype.call.bind(DataView.prototype.setUint16),
      wC: (x0,x1) => x0.attachShadow(x1),
      wD: x0 => new Intl.Locale(x0),
      wE: (o, p, r) => o.replace(p, () => r),
      wF: (x0,x1) => x0.adoptText(x1),
      wG: x0 => x0.parentElement,
      wH: x0 => x0.content,
      wI: (x0,x1,x2) => x0.open(x1,x2),
      wJ: x0 => x0.name,
      wK: x0 => ({alpha: x0}),
      wL: x0 => x0.blob(),
      wM: (x0,x1,x2) => new ImageData(x0,x1,x2),
      wN: (x0,x1) => { x0.oncomplete = x1 },
      wO: (x0,x1,x2) => globalThis.Atomics.wait(x0,x1,x2),
      wP: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      wQ: x0 => x0.oldVersion,
      wR: x0 => x0.location,
      wS: (x0,x1) => x0.canShare(x1),
      wT: (x0,x1) => { x0.transform = x1 },
      wU: () => new Map(),
      wV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      wW: x0 => x0.x,
      wX: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      wY: (x0,x1) => { x0.center = x1 },
      wZ: () => globalThis.libphonenumber.PhoneNumberUtil.getInstance(),
      wa: x0 => x0.name,
      wb: (x0,x1) => x0.debug(x1),
      wc: x0 => x0.phoneNumber,
      wd: (x0,x1,x2) => ({id: x0,name: x1,request: x2}),
      we: x0 => x0.metadata,
      wf: x0 => x0.assetBase,
      x: x0 => x0.random(),
      xB: Function.prototype.call.bind(DataView.prototype.getUint16),
      xC: (x0,x1) => x0.createElement(x1),
      xD: x0 => x0.region,
      xE: (o, p, r) => o.replaceAll(p, () => r),
      xF: x0 => x0.first(),
      xG: (x0,x1) => x0.querySelectorAll(x1),
      xH: x0 => x0.document,
      xI: (x0,x1) => x0.send(x1),
      xJ: x0 => x0.repetitionCount,
      xK: (x0,x1,x2) => x0.getContext(x1,x2),
      xL: (x0,x1) => x0.appendChild(x1),
      xM: (x0,x1) => x0.getContext(x1),
      xN: (x0,x1) => x0.objectStore(x1),
      xO: (x0,x1,x2) => globalThis.Atomics.notify(x0,x1,x2),
      xP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return wasmFunction(f,arguments.length,x0,x1,x2,x3) }),
      xQ: () => globalThis.indexedDB,
      xR: (x0,x1) => x0.getModifierState(x1),
      xS: (x0,x1) => x0.share(x1),
      xT: x0 => x0.getSettings(),
      xU: (x0,x1,x2) => x0.set(x1,x2),
      xV: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      xW: (x0,x1,x2) => x0.fromLatLngToPoint(x1,x2),
      xX: x0 => ({createHTML: x0}),
      xY: (x0,x1) => { x0.zoom = x1 },
      xZ: x0 => globalThis.libPhoneNumberFlutterGetRegionDisplayNames(x0),
      xa: x0 => globalThis.firebase_core.getApp(x0),
      xb: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      xc: x0 => x0.lastSignInTime,
      xd: (x0,x1) => x0.postMessage(x1),
      xe: x0 => x0.toArray(),
      xf: x0 => x0.loader,
      y: () => globalThis.Math,
      yB: o => o instanceof Int16Array,
      yC: x0 => x0.scale,
      yD: x0 => x0.script,
      yE: x0 => x0.deltaMode,
      yF: x0 => x0.next(),
      yG: (x0,x1) => x0.removeProperty(x1),
      yH: (x0,x1,x2) => x0.insertBefore(x1,x2),
      yI: x0 => x0.send(),
      yJ: x0 => x0.frameCount,
      yK: (x0,x1,x2,x3,x4) => x0.fillRect(x1,x2,x3,x4),
      yL: x0 => x0.click(),
      yM: (x0,x1) => new OffscreenCanvas(x0,x1),
      yN: (x0,x1) => x0.sqlite3_finalize(x1),
      yO: (x0,x1,x2) => globalThis.Atomics.store(x0,x1,x2),
      yP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1,x2,x3) { return wasmFunction(f,arguments.length,x0,x1,x2,x3) }),
      yQ: (x0,x1) => ({name: x0,length: x1}),
      yR: x0 => x0.metaKey,
      yS: x0 => x0.remove(),
      yT: x0 => x0.facingMode,
      yU: (x0,x1) => x0.querySelector(x1),
      yV: (x0,x1) => { x0.preload = x1 },
      yW: (x0,x1) => x0.fromLatLngToPoint(x1),
      yX: (x0,x1,x2) => x0.createPolicy(x1,x2),
      yY: x0 => new google.maps.marker.AdvancedMarkerElement(x0),
      yZ: x0 => x0.getSupportedRegions(),
      ya: () => globalThis.firebase_core.getApp(),
      yb: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      yc: x0 => x0.creationTime,
      yd: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      ye: x0 => x0.toUint8Array(),
      yf: () => globalThis._flutter,
      z: (x0,x1) => x0.prepend(x1),
      zB: Function.prototype.call.bind(DataView.prototype.setInt16),
      zC: x0 => x0.visualViewport,
      zD: x0 => x0.language,
      zE: x0 => x0.deltaY,
      zF: x0 => x0.current(),
      zG: (x0,x1) => x0.add(x1),
      zH: x0 => x0.id,
      zI: x0 => x0.abort(),
      zJ: x0 => x0.selectedTrack,
      zK: (x0,x1,x2) => ({canvasContext: x0,viewport: x1,enableWebGL: x2}),
      zL: (x0,x1) => x0.removeChild(x1),
      zM: x0 => x0.allocationSize(),
      zN: (x0,x1) => x0.sqlite3_reset(x1),
      zO: (x0,x1,x2) => x0.setInt32(x1,x2),
      zP: (wasmFunction,f) => finalizeWrapper(f, function(x0,x1) { return wasmFunction(f,arguments.length,x0,x1) }),
      zQ: (x0,x1) => x0.update(x1),
      zR: x0 => x0.altKey,
      zS: (o, a) => o + a,
      zT: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      zU: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      zV: x0 => x0.src,
      zW: x0 => x0.getProjection(),
      zX: (x0,x1) => x0.createHTML(x1),
      zY: (wasmFunction,f) => finalizeWrapper(f, function(x0) { return wasmFunction(f,arguments.length,x0) }),
      zZ: (x0,x1,x2) => x0.getExampleNumberForType(x1,x2),
      za: x0 => x0.updated,
      zb: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      zc: x0 => x0.metadata,
      zd: (x0,x1) => { x0.onmessage = x1 },
      ze: () => globalThis.firebase_firestore.Bytes,

    };

    const baseImports = {
      _: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
